stages: 
  - build
  - test

default:
  before_script:
    - docker info

website_build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY
    - echo $CI_PROJECT_NAME
    - echo $CI_PROJECT_NAMESPACE
    - echo $CI_PROJECT_PATH
    - echo $CI_PROJECT_ROOT_NAMESPACE
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_REGISTRY_PASSWORD |docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

website_test: 
  image: docker:latest
  stage: test
  services:
    - docker:dind
  script:
    - pwd
    - yarn test